### ISSUE TITLE
Add invert to calender icon in input field

### ISSUE THREAD

**Issue by tq-bit** [tq-bit/vitepress-components#2]
To display the calender icon on dark background (cannot be colored any other way known to me)

@media (prefers-color-scheme: dark) {
  input::-webkit-calendar-picker-indicator {
    filter: invert(100%);
  }
}

**Comment by tq-bit** [comment]
alternative: add the following to `App.vue` or `main.js`: 

```css
html.dark-theme input[type="date"]::-webkit-calendar-picker-indicator {
  filter: invert(100%);
}
```
